tinymce.addI18n('ru', {
  "Redo": "Повторить",
  "Undo": "Отменить",
  "Cut": "Вырезать",
  "Copy": "Копировать",
  "Paste": "Вставить",
  "Select all": "Выбрать все",
  "New document": "Новый документ",
  "Ok": "ОК",
  "Cancel": "Отмена",
  "Visual aids": "Визуальные подсказки",
  "Bold": "Полужирный",
  "Italic": "Курсив",
  "Underline": "Подчеркнутый",
  "Strikethrough": "Зачеркнутый",
  "Superscript": "Надстрочный",
  "Subscript": "Подстрочный",
  "Clear formatting": "Очистить форматирование",
  "Remove": "Удалить",
  "Align left": "По левому краю",
  "Align center": "По центру",
  "Align right": "По правому краю",
  "No alignment": "Без выравнивания",
  "Bullet list": "Маркированный список",
  "Numbered list": "Нумерованный список",
  "Decrease indent": "Уменьшить отступ",
  "Increase indent": "Увеличить отступ",
  "Close": "Закрыть",
  "Formats": "Форматы",
  "Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X/C/V keyboard shortcuts instead.": "Ваш браузер не поддерживает прямой доступ к буферу обмена. Используйте сочетания клавиш Ctrl+X/C/V.",
  "Headers": "Заголовки",
  "Header 1": "Заголовок 1",
  "Header 2": "Заголовок 2",
  "Header 3": "Заголовок 3",
  "Header 4": "Заголовок 4",
  "Header 5": "Заголовок 5",
  "Header 6": "Заголовок 6",
  "Headings": "Заголовки",
  "Heading 1": "Заголовок 1",
  "Heading 2": "Заголовок 2",
  "Heading 3": "Заголовок 3",
  "Heading 4": "Заголовок 4",
  "Heading 5": "Заголовок 5",
  "Heading 6": "Заголовок 6",
  "Preformatted": "Предварительно отформатированный",
  "Div": "Div",
  "Pre": "Pre",
  "Code": "Код",
  "Paragraph": "Параграф",
  "Blockquote": "Цитата",
  "Inline": "Встроенный",
  "Blocks": "Блоки",
  "Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.": "Вставка теперь в режиме простого текста. Содержимое будет вставляться как простой текст, пока вы не отключите эту опцию.",
  "Fonts": "Шрифты",
  "Font sizes": "Размеры шрифтов",
  "Class": "Класс",
  "Browse for an image": "Найти изображение",
  "OR": "ИЛИ",
  "Drop an image here": "Перетащите изображение сюда",
  "Upload": "Загрузить",
  "Uploading image": "Загрузка изображения",
  "Image description": "Описание изображения",
  "Source": "Источник",
  "Dimensions": "Размеры",
  "Constrain proportions": "Сохранять пропорции",
  "General": "Общие",
  "Advanced": "Дополнительно",
  "Style": "Стиль",
  "Vertical space": "Вертикальный отступ",
  "Horizontal space": "Горизонтальный отступ",
  "Border": "Граница",
  "Insert image": "Вставить изображение",
  "Image": "Изображение",
  "Image URL": "URL изображения",
  "Alternative description": "Альтернативное описание",
  "Title": "Заголовок",
  "Insert link": "Вставить ссылку",
  "Link": "Ссылка",
  "Text to display": "Текст для отображения",
  "Url": "URL",
  "Open link in...": "Открыть ссылку в...",
  "Current window": "Текущее окно",
  "None": "Нет",
  "New window": "Новое окно",
  "Open link": "Открыть ссылку",
  "Remove link": "Удалить ссылку",
  "Anchors": "Якоря",
  "Insert template": "Вставить шаблон",
  "Templates": "Шаблоны",
  "Background color": "Цвет фона",
  "Text color": "Цвет текста",
  "Show blocks": "Показать блоки",
  "Show invisible characters": "Показать невидимые символы",
  "Words: {0}": "Слов: {0}",
  "Insert": "Вставить",
  "File": "Файл",
  "Edit": "Редактировать",
  "Rich Text Area": "Область форматированного текста",
  "Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help": "Область форматированного текста. Нажмите ALT-F9 для меню. Нажмите ALT-F10 для панели инструментов. Нажмите ALT-0 для справки.",
  "Tools": "Инструменты",
  "View": "Вид",
  "Table": "Таблица",
  "Format": "Формат"
});
