name: deploy
on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node Setup
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Remove admin folder from static export
        run: rm -rf ./src/app/admin

      - name: Build and Static HTML Export
        run: npm run build
        env:
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
          NEXT_EXPORT_TYPE: export

      - name: Enable custom domain
        run: cp CNAME ./out

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: out
